ids = ['UCoOae5nYA7VqaXzerajD0lg',
       'UCBJycsmduvYEL83R_U4JriQ',
       'UCXuqSBlHAE6Xw-yeJA0Tunw',
       'UCPDXXXJj9nax0fr0Wfc048g',
       'UCtinbF-Q-fVthA0qrFQTgXQ',
       'UC78cxCAcp7JfQPgKxYdyGrg',
       'UCo8bcnLyZH8tBIH9V1mLgqQ',
       'UCGwu0nbY2wSkW8N-cghnLpA',
       'UCX6OQ3DkcsbYNE6H8uQQuVA',
       'UClFSU9_bUb4Rc6OYfTt5SPw',
       'UCtoaZpBnrd0lhycxYJ4MNOQ',
       'UCRijo3ddMTht_IHyNSNXpNQ',
       'UCJkMlOu7faDgqh4PfzbpLdg',
       'UC2C_jShtL725hvbm1arSV9w',
       'UCqECaJ8Gagnn7YCbPEzWH6g',
       'UC0C-w0YjGpqDXGB8IHb662A',
       'UC9CoOnJkIBMdeijd9qYoT_g',
       'UCt7fwAhXDy3oNFTAzF2o8Pw',
       'UC7_YxT-KID8kRbqZo7MyscQ',
       'UCTkXRDQl0luXxVQrRQvWS6w',
       'UCsvn_Po0SmunchJYOWpOxMg',
       'UCYzPXprvl5Y-Sf0g4vX-m6g',
       'UC6nSFpj9HTCZ5t-N3Rm3-HA',
       'UCX6b17PVsYBQ0ip5gyeme-Q',
       'UCHnyfMqiRRG1u-2MsSQLbXA',
       'UCoxcjq-8xIDTYp3uz647V5A',
       'UCJFp8uSYCjXOMnkUyb3CQ3Q',
       'UCWwqHwqLSrdWMgp5DZG5Dzg',
       'UCwWhs_6x42TyRM4Wstoq8HA',
       'UC16niRr50-MSBwiO3YDb3RA',
       'UCiWLfSweyRNmLpgEHekhoAg',
       'UCWJ2lWNubArHWmf3FIHbfcQ',
       'UCkvK_5omS-42Ovgah8KRKtg',
       'UCoLUji8TYrgDy74_iiazvYA',
       'UCHL9bfHTxCMi-7vfxQ-AYtg',
       'UCoal_hpPIPAnWlG-kWHLheA',
       'UCY1kMZp36IQSyNx_9h4mpCg']

new_channels = ["Unbox Therapy", "Cody Ko", "H3H3 Productions", "Roman Atwood", "Domics", "OneyPlays",
                "Kurzgesagt – In a Nutshell", "The Majority Report with Sam Seder",
                "MLB", "CNN", "NBC News", "Gordon Ramsay", "Bon Appétit", "Binging with Babish",
                "Billie Eilish", "PewDiePie", "It's Okay To Be Smart", "TED-Ed", "James Charles",
                "Wendover Productions", "CBS News", "Good Mythical Morning", "Rhett & Link", "Doug DeMuro",
                "Drew Gooden", "Danny Gonzales", "Vox", "VICE", "Guardian News", "Kurtis Connor", "Jubilee",
                "PragerU", "JerryRigEverything", "penguinz0", "LastWeekTonight", "Shane", "MeatCanyon", "Jake Paul",
                "The Game Theorists", "Saturday Night Live", "PBS Space Time", "Hongyu ASMR 홍유", "Gibi ASMR",
                "The Tonight Show Starring Jimmy Fallon"]


new_channel_ids = ["UCsTcErHg8oDvUnTzoqsYeNw", "UCfp86n--4JvqKbunwSI2lYQ", "UCDWIvJwLJsE4LG1Atne2blQ",
                   "UC-SV8-bUJfXjrRMnp7F8Wzw", "UCn1XB-jvmd9fXMzhiA6IR0w", "UCO1ITICo8MLHGAXR1uzFwjA",
                   "UCsXVk37bltHxD1rDPwtNM8Q", "UC-3jIAlnQmbbVMV6gR7K8aQ", "UCoLrcjPV5PbUrUyXq5mjc_A",
                   "UCupvZG-5ko_eiXAupbDfxWw", "UCeY0bbntWzzVIaj2z3QigXg", "UCIEv3lZ_tNXHzL3ox-_uUGQ",
                   "UCbpMy0Fg74eXXkvxJrtEn3w", "UCJHA_jMfCvEnv-3kRjTCQXw", "UCiGm_E4ZwYSHV3bcW1pnSeQ",
                   "UC-lHJZR3Gqxm24_Vd_AJ5Yw", "UCH4BNI0-FOK2dMXoFtViWHw", "UCsooa4yRKGN_zEE8iknghZA",
                   "UCucot-Zp428OwkyRm2I7v2Q", "UC9RM-iSvTu1uPJb8X5yp3EQ", "UC8p1vwvWtl6T73JiExfWs1g",
                   "UC4PooiX37Pld1T8J5SYT-SQ", "UCbochVIwBCzJb9I2lLGXGjQ", "UCsqjHFMB_JYTaEnf_vmTNqg",
                   "UCTSRIY3GLFYIpkR2QwyeklA", "UCSUf5_EPEfl4zlBKZHkZdmw", "UCLXo7UDZvByw2ixzpQCufnA",
                   "UCn8zNIfYAQNdrFRrr8oibKw", "UCIRYBXDze5krPDzAEOxFGVA", "UC7zsxKqd5MicTf4VhS9Y74g",
                   "UCJjSDX-jUChzOEyok9XYRJQ", "UCZWlSUNDvCCS1hBiXV0zKcA", "UCWFKCr40YwOZQx8FHU_ZqqQ",
                   "UCq6VFHwMzcMXbuKyG7SQYIg", "UC3XTzVzaHQEd30rQbuvCtTQ", "UCV9_KinVpV-snHe3C3n1hvA",
                   "UC91V6D3nkhP89wUb9f_h17g", "UCcgVECVN4OKV6DH1jLkqmcA", "UCo_IB5145EVNcf8hw1Kku7w",
                   "UCqFzWxSCi39LnW1JKFR3efg", "UC7_gcs09iThXybpVgjHZ_7g", "UCxtLc0Jqq3SKBWlIXM_OC9g",
                   "UCE6acMV3m35znLcf0JGNn7Q", "UC8-Th83bH_thdKZDJCrn88g", 'UCoOae5nYA7VqaXzerajD0lg',
                   'UCBJycsmduvYEL83R_U4JriQ',
                   'UCXuqSBlHAE6Xw-yeJA0Tunw',
                   'UCPDXXXJj9nax0fr0Wfc048g',
                   'UCtinbF-Q-fVthA0qrFQTgXQ',
                   'UC78cxCAcp7JfQPgKxYdyGrg',
                   'UCo8bcnLyZH8tBIH9V1mLgqQ',
                   'UCGwu0nbY2wSkW8N-cghnLpA',
                   'UCX6OQ3DkcsbYNE6H8uQQuVA',
                   'UClFSU9_bUb4Rc6OYfTt5SPw',
                   'UCtoaZpBnrd0lhycxYJ4MNOQ',
                   'UCRijo3ddMTht_IHyNSNXpNQ',
                   'UCJkMlOu7faDgqh4PfzbpLdg',
                   'UC2C_jShtL725hvbm1arSV9w',
                   'UCqECaJ8Gagnn7YCbPEzWH6g',
                   'UC0C-w0YjGpqDXGB8IHb662A',
                   'UC9CoOnJkIBMdeijd9qYoT_g',
                   'UCt7fwAhXDy3oNFTAzF2o8Pw',
                   'UC7_YxT-KID8kRbqZo7MyscQ',
                   'UCTkXRDQl0luXxVQrRQvWS6w',
                   'UCsvn_Po0SmunchJYOWpOxMg',
                   'UCYzPXprvl5Y-Sf0g4vX-m6g',
                   'UC6nSFpj9HTCZ5t-N3Rm3-HA',
                   'UCX6b17PVsYBQ0ip5gyeme-Q',
                   'UCHnyfMqiRRG1u-2MsSQLbXA',
                   'UCoxcjq-8xIDTYp3uz647V5A',
                   'UCJFp8uSYCjXOMnkUyb3CQ3Q',
                   'UCWwqHwqLSrdWMgp5DZG5Dzg',
                   'UCwWhs_6x42TyRM4Wstoq8HA',
                   'UC16niRr50-MSBwiO3YDb3RA',
                   'UCiWLfSweyRNmLpgEHekhoAg',
                   'UCWJ2lWNubArHWmf3FIHbfcQ',
                   'UCkvK_5omS-42Ovgah8KRKtg',
                   'UCoLUji8TYrgDy74_iiazvYA',
                   'UCHL9bfHTxCMi-7vfxQ-AYtg',
                   'UCoal_hpPIPAnWlG-kWHLheA',
                   'UCY1kMZp36IQSyNx_9h4mpCg']
